### ISSUE TITLE
Tantivy: required or optional dependency?

### ISSUE THREAD

**Issue by adamcallison** [opensanctions/nomenklatura#158]
Recent versions of nomenklatura list `tantivy` as [an optional dependency](https://github.com/opensanctions/nomenklatura/blob/f9d6d2309f2af9eb44b887dcc29aab5e8b60e9a6/setup.py#L69), and yet the root level `__init__.py` [imports](https://github.com/opensanctions/nomenklatura/blob/f9d6d2309f2af9eb44b887dcc29aab5e8b60e9a6/nomenklatura/__init__.py#L6) a module that depends on it, making the library unusable without installing `tantivy`. What is the intended behaviour here?

**Comment by pudo** [comment]
hello @adamcallison - I think this should be fixed now, it was a bit under-tested. Let me know if you have any questions about nomenklatura ... it's very much a construction site.
